
title: My Resume
url: 'http://arvind.seshan.org'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Arvind Seshan  ## put your name
title: 'Student'  ## your title
location: Pittsburgh , PA


## Social Profiles
facebook: https://www.facebook.com/arvindseshan04 ## your facebook account url
twitter:  ## your twitter account url
linkedin: https://www.linkedin.com/in/arvind-seshan-368a85235/  ## your linkedin account url
website: http://www.primelessons.org
youtube: https://www.youtube.com/channel/UCMpY-AqxFcQ0lesR3tS-FJw
github: https://github.com/arvindseshan



# Update all the sections by editing the files inside _includes folder.
